# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SACEMA
subtitle: Measles dynamics
email: measlesInfo@sacema.org
description: > # this means to ignore newlines until "baseurl:"
  Click above to learn more
baseurl: "/measles" # the subpath of your site, e.g. /blog
url: "http://www.sacema.org" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: SACEMAdirector
#github_username:  BlackrockDigital
#facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: 19 Jonkershoek Road
address_city: Stellenbosch
address_state: 7600
address_zip: South Africa

# Build settings
markdown: kramdown
exclude: [README.md,LICENSE,run.sh]
